# Generated by Django 4.1.10 on 2023-10-25 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_camera"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("trip_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Camera",
        ),
        migrations.RemoveField(
            model_name="location",
            name="title",
        ),
        migrations.RemoveField(
            model_name="location",
            name="trip_date",
        ),
        migrations.AddField(
            model_name="location",
            name="date_range",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="location_name",
            field=models.CharField(default="location1", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name="trip",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="dashboard.user",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="trip",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="dashboard.trip",
            ),
            preserve_default=False,
        ),
    ]
