# Generated by Django 4.1.10 on 2023-11-09 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_rename_name_user_username_remove_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="user",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Trip",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
