# Generated by Django 4.1.10 on 2023-10-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_trip_user_delete_camera_remove_location_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="date_range",
        ),
        migrations.AddField(
            model_name="location",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
