# Generated by Django 4.1.10 on 2023-11-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_remove_location_date_range_location_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="passwordplaceholder", max_length=255),
            preserve_default=False,
        ),
    ]
